<?php
require_once __DIR__ . '/../config.php';
require_once __DIR__ . '/../includes/Database.php';
require_once __DIR__ . '/../includes/ContentRepository.php';
require_once __DIR__ . '/../includes/ContentPresenter.php';
$slug=(string)($_GET['slug']??''); $post=null;
if(preg_match('/^[a-z0-9]+(?:-[a-z0-9]+)*$/',$slug)){try{$repository=new ContentRepository(Database::getInstance()->getConnection());$post=$repository->findPublishedBySlug('resource',$slug);}catch(Throwable $error){$post=null;}}
if($post===null){http_response_code(404);$currentPage='resources';$pageTitle='자료를 찾을 수 없습니다 - '.$site['name'];$pageDescription='요청한 자료를 찾을 수 없습니다.';$pageUrl=url('resources/'.rawurlencode($slug));require_once __DIR__.'/../includes/header.php';echo '<section class="section"><div class="container"><p class="content-empty">요청한 자료를 찾을 수 없습니다.</p></div></section>';require_once __DIR__.'/../includes/footer.php';exit;}
$currentPage='resources';$pageTitle=$post['title'].' - '.$site['name'];$pageDescription=(string)$post['summary'];$pageUrl=url('resources/'.$post['slug']);require_once __DIR__.'/../includes/header.php';
?>
<article class="content-detail"><header class="page-header"><div class="container"><a class="content-back" href="<?php echo htmlspecialchars(url('resources'), ENT_QUOTES, 'UTF-8'); ?>">← 자료실</a><div class="content-kicker"><?php echo htmlspecialchars(resourceCategoryLabel((string)$post['resource_category']), ENT_QUOTES, 'UTF-8'); ?></div><h1><?php echo htmlspecialchars($post['title'], ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); ?></h1><p><?php echo htmlspecialchars((string)$post['summary'], ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); ?></p><div class="content-meta"><time datetime="<?php echo htmlspecialchars($post['content_date'], ENT_QUOTES, 'UTF-8'); ?>"><?php echo htmlspecialchars($post['content_date'], ENT_QUOTES, 'UTF-8'); ?></time></div></div></header><div class="section"><div class="container content-reading"><div class="plain-content"><?php echo renderPlainText((string)$post['summary']); ?></div><div class="resource-action"><?php if(!empty($post['file_id'])&&$post['file_purpose']==='attachment'): ?><a class="btn-primary" href="<?php echo htmlspecialchars(url('downloads/'.(int)$post['file_id']), ENT_QUOTES, 'UTF-8'); ?>">자료 다운로드 · <?php echo htmlspecialchars(strtoupper(pathinfo((string)$post['file_original_name'],PATHINFO_EXTENSION)), ENT_QUOTES, 'UTF-8'); ?> · <?php echo number_format(((int)$post['file_byte_size'])/1048576,1); ?> MiB</a><?php elseif(!empty($post['external_url'])): ?><a class="btn-primary" href="<?php echo htmlspecialchars((string)$post['external_url'], ENT_QUOTES, 'UTF-8'); ?>" target="_blank" rel="noopener noreferrer">외부 자료 보기 · <?php echo htmlspecialchars(externalLinkHost((string)$post['external_url']), ENT_QUOTES, 'UTF-8'); ?> ↗</a><?php endif; ?></div></div></div></article>
<?php require_once __DIR__ . '/../includes/footer.php'; ?>
